using AutoMapper;
using Hairlytics.Application.DTOs.BookingDTOs;
using Hairlytics.Application.DTOs.CategoryDTOs;
using Hairlytics.Application.DTOs.ServiceDTOs;
using Hairlytics.Application.DTOs.UserDTOs;
using Hairlytics.Application.DTOs.VendorDocumentDTOs;
using Hairlytics.Application.DTOs.VendorProfileDTOs;
using Hairlytics.Application.DTOs.VendorStaffDTOs;
using Hairlytics.Application.DTOs.VendroGalleryDTOs;
using Hairlytics.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Hairlytics.Application.Mapping
{
    public class MappingProfile : Profile
    {
        public MappingProfile() {

            // =========================
            // USER MAPPINGS
            // =========================

            //  Actual to Expected

            // Entity → Response DTO
           CreateMap<User, UserResponseDto>()
                .ForMember(dest => dest.VendorProfileResponseDto,
                    opt => opt.MapFrom(src => src.VendorProfile));

            // Create DTO → Entity
            CreateMap<UserCreateDto, User>();

            // Update DTO → Entity
            //CreateMap<UserUpdateDto, User>()
            //  .ForMember(dest => dest.VendorProfile, opt => opt.Ignore()) 
            //  .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));


            CreateMap<UserUpdateDto, User>()
                .ForMember(dest => dest.VendorProfile, opt => opt.MapFrom(src => src.VendorProfileUpdateDto))
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // =========================
            // VENDOR PROFILE MAPPINGS
            // =========================

            // Entity → Response DTO
            //CreateMap<VendorProfile, VendorProfileResponseDto>();

            CreateMap<VendorProfile, VendorProfileResponseDto>()
                .ForMember(dest => dest.VendorDocumentResponseDto,
                opt => opt.MapFrom(src => src.Documents));


            CreateMap<VendorProfileResponseDto, VendorProfile>();

            // Create DTO → Entity
            CreateMap<VendorProfileCreateDto, VendorProfile>();

            // Update DTO → Entity
            CreateMap<VendorProfileUpdateDto, VendorProfile>()
              .ForMember(dest => dest.Documents, opt => opt.Ignore()) 
              .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));


            // =========================
            // VENDOR DOCUMENT MAPPINGS 
            // =========================

            CreateMap<VendorDocument, VendorDocumentResponseDto>();           
            CreateMap<VendorDocumentCreateDto, VendorDocument>();
            CreateMap<VendorDocumentUpdateDto, VendorDocument>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));


            // create category DTO to Category 

            CreateMap<CategoryCreateDto, Category>();
            CreateMap<Category, CategoryResponseDto>();

            // create service DTO to entity  and entity to dto

            CreateMap<ServiceCreateDto, Service>();
            CreateMap<Service, ServiceResponseDto>()
                .ForMember(dest => dest.CategoryResponseDto,
                opt => opt.MapFrom(src => src.Category));

            // create vendor gallery DTO to entity  and entity to dto

            CreateMap<VendorGalleryCreateDto, VendorGallery>();
            CreateMap<VendorGallery, VendorGalleryResponseDto>();


            CreateMap<VendorStaffCreateDto, VendorStaff>()
                .ForMember(dest => dest.ProfileImageUrl, opt => opt.Ignore()) // 🔥 ignore image
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(_ => DateTime.Now))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(_ => DateTime.Now))
                .ForMember(dest => dest.Rating, opt => opt.MapFrom(_ => 0))
                .ForMember(dest => dest.TotalReviews, opt => opt.MapFrom(_ => 0))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(_ => true))
                .ForMember(dest => dest.IsAvailable, opt => opt.MapFrom(_ => true));


            // entity to dto
            CreateMap<VendorStaff, VendorStaffResponseDto>();

            CreateMap<StaffAvailability, StaffAvailabilityResponseDto>();

            CreateMap<StaffAvailabilityCreateDto, StaffAvailability>()
                .ForMember(dest => dest.StaffId, opt => opt.Ignore())
                .AfterMap((src, dest) =>
                {
                    if (src.IsOffDay)
                    {
                        dest.StartTime = TimeSpan.Zero;
                        dest.EndTime = TimeSpan.Zero;
                    }
                });


            CreateMap<BookingCreateDto, Booking>()
            // Ignore the ID as it's generated by the DB
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            // Map the List<int> ServiceIds to List<BookedService> entities
            .ForMember(dest => dest.BookedService, opt => opt.MapFrom(src =>
                src.ServiceIds.Select(id => new BookedService
                {
                    ServiceId = id
                }).ToList()))
            // Ensure system fields are ignored or set to defaults
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(_ => DateTime.Now))
            .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(_ => DateTime.Now))
            .ForMember(dest => dest.Status, opt => opt.Ignore()) // Defaults to Pending in model
            .ForMember(dest => dest.PaymentStatus, opt => opt.Ignore()); // Defaults to Pending
        }

        

    }
}
